### ISSUE TITLE
Offset not working for /rpc "search_workspace" method

### ISSUE THREAD

**Issue by jayrbolton** [kbase/search_api2#30]
As reported by Dakota

**Comment by dakotablair** [comment]
It seems there is no clause for the paging parameter in search_workspace in this file: https://github.com/kbase/search_api2/blob/develop/src/search2_conversion/convert_params.py

**Comment by jayrbolton** [comment]
Good call. Just added that and updating tests.

**Comment by jayrbolton** [comment]
PR #31
